spring.application.name=account-service

spring.datasource.url=jdbc:postgresql://localhost:5432/baraza_core
spring.datasource.username=baraza
spring.datasource.password=Baraza@2026

spring.jpa.hibernate.ddl-auto=update