spring.application.name=baraza-payment

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5435/baraza_payment
spring.datasource.username=baraza
spring.datasource.password=baraza

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
payment.simulated-db-delay-ms=0