spring.application.name=transaction-service

spring.datasource.url=jdbc:postgresql://localhost:5434/baraza_transactions
spring.datasource.username=baraza
spring.datasource.password=Baraza@2026

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info
