spring.application.name=transaction-service

spring.datasource.url=jdbc:postgresql://baraza-transaction-postgres:5432/baraza_transactions
spring.datasource.username=baraza
spring.datasource.password=Baraza@2026

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info
account.service.url=${ACCOUNT_SERVICE_URL:http://localhost:8081}
